Update Git repository using egup-single

diff --git a/support/post-default-prepare b/support/post-default-prepare
--- a/support/post-default-prepare
+++ b/support/post-default-prepare
@@ -1,4 +1,5 @@
 if [[ -e support/.cache-build ]]; then
-support/build-scripts/build --cache --somewhat-verbose || die "Build failed!"
-
-support/build-scripts/build --somewhat-verbose || die "Build failed!"
+    support/build-scripts/build --cache --somewhat-verbose || die "Build failed!"
+else
+    support/build-scripts/build --somewhat-verbose || die "Build failed!"
+fi
