Update Git repository using egup-single

diff --git a/support/prepare b/support/prepare
--- a/support/prepare
+++ b/support/prepare
@@ -9,7 +9,7 @@ fail() {
     #NOTE: MAINTENANCE: Manual error printing
     if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
         printf '%b' '\033[1;31m' >&2
-        echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
+        echo "ERROR: ember-shared is not properly installed! It must be installed before installing Crystallize." >&2
         printf '%b' '\033[0m' >&2
         exit 1
     fi
@@ -29,6 +29,7 @@ if [[ "$OSTYPE" = darwin* ]]; then
     find scripts -type f -exec perl -0777 -p -i -e 's/readlink /greadlink /g' {} \;
     find scripts -type f -exec perl -0777 -p -i -e 's/dirname /gdirname /g' {} \;
     find scripts -type f -exec perl -0777 -p -i -e 's/sort /gsort /g' {} \;
+    find scripts -type f -exec perl -0777 -p -i -e 's/stdbuf /gstdbuf /g' {} \;
     find scripts -type f -exec perl -0777 -p -i -e 's/sha256sum /gsha256sum /g' {} \;
     find scripts -type f -exec perl -0777 -p -i -e 's/sha512sum /gsha512sum /g' {} \;
     find scripts -type f -exec perl -0777 -p -i -e 's/ncdu /8731d097a5ed41149c7ffb67756c310e /g' {} \;
