Update Git repository using egup-single

diff --git a/support/test b/support/test
--- a/support/test
+++ b/support/test
@@ -5,4 +5,8 @@ if [[ -f ./support/.build-type ]]; then
 fi
 
 # data/tests/stagel-run-tests are run prior to building, during prepare
-data/tests/eite-run-tests || die "EITE tests failed!"
+if [[ -z "$buildType" ]] || [[ "portable" == "$buildType" ]]; then
+    data/tests/eite-run-tests || die "EITE tests failed!"
+fi
+
+true
