Update Git repository using egup-single

diff --git a/support/wasm-toolchain-build b/support/wasm-toolchain-build
--- a/support/wasm-toolchain-build
+++ b/support/wasm-toolchain-build
@@ -5,52 +5,10 @@ source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A 
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
-# Build third-party components
-[[ -d ./build-temp/distfiles ]] || die "Make sure the required dependency files are in ./build-temp/distfiles, or run build-scripts/dist-fetch to get them from your /usr/portage."
-
-rm -rf ./build-temp/unpacked
-cp -r ./build-temp/distfiles ./build-temp/unpacked
-
 source ./support/build-scripts/dist-versions || die
+./support/build-scripts/dist-unpack || die "Could not run dist-unpack."
 
-# Unpack distfiles
-
-(
-cd ./build-temp/unpacked || die
-
-echo "Unpacking Binaryen"
-tar xozf ./binaryen-"$myBinaryenVersion".tar.gz
-rm ./binaryen-"$myBinaryenVersion".tar.gz
-# Leave the .zip version alone; that's for pretending to be the Emscripten port system
-
-echo "Unpacking Emscripten"
-tar xozf ./emscripten-"$myEmscriptenCommit".tar.gz
-rm ./emscripten-"$myEmscriptenCommit".tar.gz
-rm -r ./emscripten-"$myEmscriptenCommit"/tools/node_modules
-rm -r ./emscripten-"$myEmscriptenCommit"/tools/eliminator
-rm -r ./emscripten-"$myEmscriptenCommit"/third_party/closure-compiler
-rm -r ./emscripten-"$myEmscriptenCommit"/third_party/html-minifier
-rm -r ./emscripten-"$myEmscriptenCommit"/third_party/ply
-rm -r ./emscripten-"$myEmscriptenCommit"/third_party/websockify
-rm ./emscripten-"$myEmscriptenCommit"/third_party/lzma.js/lzma-full.js
-rm ./emscripten-"$myEmscriptenCommit"/third_party/lzma.js/lzma-decoder.js
-
-echo "Unpacking wabt dependencies"
-tar xozf ./googletest-"$myGoogletestVersion".tar.gz
-rm ./googletest-"$myGoogletestVersion".tar.gz
-tar xozf ./python-lex-yacc-"$myPlyVersion".tar.gz
-rm ./python-lex-yacc-"$myPlyVersion".tar.gz
-tar xozf ./WebAssembly-testsuite-"$myTestsuiteCommit".tar.gz
-rm WebAssembly-testsuite-"$myTestsuiteCommit".tar.gz
-
-echo "Unpacking wabt"
-tar xozf ./wabt-"$myWabtVersion".tar.gz
-rm ./wabt-"$myWabtVersion".tar.gz
-rm -r ./wabt-"$myWabtVersion"/src/prebuilt
-rm -r ./wabt-"$myWabtVersion"/third_party
-rm -r ./wabt-"$myWabtVersion"/demo/third_party
-rm ./wabt-"$myWabtVersion"/demo/libwabt.js
-)
+# Build WebAssembly toolchain
 
 (
 
