Revert "Update Git repository using egup-single"
This reverts commit c8c047ccd4e934a770caa8555109e01539e1d2ec.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,67 +1,54 @@
-# Gets sourced by individual packages' configure scripts
+#!/usr/bin/env bash
+#set -x
+
+# Should work without ember-shared, so don't source ember_bash_setup_core or set traps that need. Only require ember_bash_setup_core.
+
+packageName="$(<package-name)"
+
+if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z "$ebs_loc" ]]; then
+    # Try automatically building an ember-shared locally to use
+    mkdir .buildsystem-temp
+    (
+        cd .buildsystem-temp || exit 1
+        git clone --depth 1 https://github.com/ethus3h/ember-shared.git
+        cd ember-shared || exit 1
+        ./configure
+        make
+    )
+    PATH="$PATH:.buildsystem-temp/ember-shared/scripts"
+    export PATH
+    if [[ -e ".buildsystem-temp/ember-shared" ]]; then
+        (
+            cd .buildsystem-temp/ember-shared || exit 1
+            make
+            make install || true
+        )
+    fi
+fi
+
+#NOTE: MAINTENANCE: Manual error printing
+if ! ebs_loc="$(type -P "ember_bash_setup_core")" || [[ -z "$ebs_loc" ]]; then
+    printf '%b' '\033[1;31m' >&2
+    echo "ERROR: ember-shared core module is not properly installed! It must be installed before installing $packageName." >&2
+    printf '%b' '\033[0m' >&2
+    exit 1
+fi
+
+# OK, ember_bash_setup_core seems to be available
+
+source ember_bash_setup_core &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup_core could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
 
 #NOTE: MAINTENANCE: Manual error printing
 trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR
 
-packageName="$(<package-name)"
-
-rm -f support/.{prefix,mandir,infodir,datadir,sysconfdir,localstatedir}
-
-currentArgPrefix=""
-while [[ -n "$1" ]]; do
-    currentArgPrefix="${1%%=*}"
-    case $currentArgPrefix in
-    --prefix)
-        printf '%s' "${1#*=}" > support/.prefix
-        ;;
-    --mandir)
-        printf '%s' "${1#*=}" > support/.mandir
-        ;;
-    --infodir)
-        printf '%s' "${1#*=}" > support/.infodir
-        ;;
-    --datadir)
-        printf '%s' "${1#*=}" > support/.datadir
-        ;;
-    --sysconfdir)
-        printf '%s' "${1#*=}" > support/.sysconfdir
-        ;;
-    --localstatedir)
-        printf '%s' "${1#*=}" > support/.localstatedir
-        ;;
-    *)
-        true
-        ;;
-    esac
-    shift
-done
-
-touch support/.module
-touch support/.prefix
-touch support/.mandir
-touch support/.infodir
-touch support/.datadir
-touch support/.datarootdir
-touch support/.sysconfdir
-touch support/.localstatedir
-touch support/.module
-
-if ! fmwtk_loc="$(type -P "futuramerlin-web-toolkit-build")" || [[ -z "$fmwtk_loc" ]]; then
-    echo $'\n'"futuramerlin-web-toolkit not found: documentation will not be built."$'\n'
+sharedDataDir="$(getEmberSharedDataDir)"
+if [[ -z "$sharedDataDir" ]]; then
+    echo "Could not get ember-shared data directory. Perhaps the installed version is too old?"
+    exit 1
 fi
-
 buildsystemDir="$(getEmberSharedDataDir)/app-buildsystem"
-
-printf '%s' "$buildsystemDir" > support/.buildsystemdir
-
-cp "$buildsystemDir/Makefile" ./
-chmod +w ./Makefile
-if [[ -e ./Makefile.extra ]]; then
-    cat ./Makefile.extra >> ./Makefile
+if ! [[ -d "$buildsystemDir" ]]; then
+    echo "Could not get ember-shared build directory. Perhaps the installed version is too old?"
+    exit 1
 fi
-
-if [[ -e support/post-default-configure ]]; then
-    source support/post-default-configure
-fi
-
-echo "Configuring complete."
+source "$buildsystemDir/configure"
