Update Git repository using egup-single

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 #set -x
 
+# Should work without ember-shared or crystallize, just in case, so don't source ember_bash_setup or set traps that need
+
+#NOTE: MAINTENANCE: Manual error printing
+trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR
+
+rm -f support/.{prefix,mandir,infodir,datadir,sysconfdir,localstatedir}
+
 currentArgPrefix=""
 while [[ -n "$1" ]]; do
     currentArgPrefix="${1%%=*}"
@@ -29,3 +36,8 @@ while [[ -n "$1" ]]; do
     esac
     shift
 done
+
+if ! fmwtk_loc="$(type -P "futuramerlin-web-toolkit-build")" || [[ -z $fmwtk_loc ]]; then
+    echo $'\n'"futuramerlin-web-toolkit not found: documentation will not be built."$'\n'
+fi
+echo "Configuring complete."
