Update Git repository using egup-single

diff --git a/cli/stagel-convert b/cli/stagel-convert
--- a/cli/stagel-convert
+++ b/cli/stagel-convert
@@ -695,6 +695,11 @@ stateStack=("root" "code")
 blockStack=("root" "")
 testParameterFound="false" # This is set to "false" usually. When a token that uses a "test" syntax (e.g. if, or any other thing that first takes a value and also starts a code block) is encountered, it stays false until something representing a value is found, at which point it is set to "true".
 
+blockStackRemoveLast() {
+    unset 'blockStack[-1]'
+    unset 'blockStack[-1]'
+}
+
 set -x
 for (( i=0; i<tokenCount; i++ )); do
     if ! (( (i+1) % 3 )); then
@@ -721,12 +726,12 @@ for (( i=0; i<tokenCount; i++ )); do
                 indent)
                     codegenIndent
                     stateStack+=("code")
-                    blockStack+=("plain-block")
+                    blockStack+=("plain-block" "")
                     ;;
                 dedent)
                     codegenDedent
                     unset 'stateStack[-1]'
-                    unset 'blockStack[-1]'
+                    blockStackRemoveLast
                     ;;
                 ident-r-*)
                     codegenRoutineName="$(asciiDecListToText "${tokens[$i]}")"
@@ -757,7 +762,7 @@ for (( i=0; i<tokenCount; i++ )); do
                 newline)
                     ;;
                 *)
-                    die "A ${tokens[$i - 1]}, ${tokens[$i]}, isn't allowed here, in ${blockStack[-1]}."
+                    die "A ${tokens[$i - 1]}, ${tokens[$i]}, isn't allowed here, in ${blockStack[-2]} ${blockStack[-1]}."
                     ;;
                 esac
                 ;;
@@ -881,8 +886,7 @@ for (( i=0; i<tokenCount; i++ )); do
                 [[ "${tokens[$i - 1]}" == "dedent" ]] && codegenDedent
                 unset 'stateStack[-1]'
                 codegenRoutineDefinitionEnd
-                unset 'blockStack[-1]'
-                unset 'blockStack[-1]'
+                blockStackRemoveLast
                 ;;
             root)
                 true
@@ -895,7 +899,7 @@ for (( i=0; i<tokenCount; i++ )); do
     fi
 done
 
-{ [[ "${#blockStack[@]}" == "1" ]] && [[ "${blockStack[1]}" == "root" ]]; } || die "Internal error: not all blocks were consumed, or too many blocks were consumed! This is a bug in the code. Remaining block stack: ${blockStack[*]}"
+{ [[ "${#blockStack[@]}" == "2" ]] && [[ "${blockStack[1]}" == "root" ]] && [[ "${blockStack[2]}" == "" ]]; } || die "Internal error: not all blocks were consumed, or too many blocks were consumed! This is a bug in the code. Remaining block stack: ${blockStack[*]}"
 
 print_r "${stateStack[@]}" >&2
 print_r "${blockStack[@]}" >&2
