Update Git repository using egup-single

diff --git a/cli/stagel-convert b/cli/stagel-convert
--- a/cli/stagel-convert
+++ b/cli/stagel-convert
@@ -900,10 +900,7 @@ for (( i=0; i<tokenCount; i++ )); do
     fi
 done
 
-print_r "${stateStack[@]}" >&2
-print_r "${blockStack[@]}" >&2
-
-{ [[ "${#blockStack[@]}" == "2" ]] && [[ "${blockStack[1]}" == "root" ]] && [[ "${blockStack[2]}" == "" ]]; } || die "Internal error: not all blocks were consumed, or too many blocks were consumed! This is a bug in the code. Remaining block stack: ${blockStack[*]}"
+{ [[ "${#blockStack[@]}" == "2" ]] && [[ "${blockStack[0]}" == "root" ]] && [[ "${blockStack[1]}" == "" ]]; } || die "Internal error: not all blocks were consumed, or too many blocks were consumed! This is a bug in the code. Remaining block stack: ${blockStack[*]}"
 
 print_r "${stateStack[@]}" >&2
 print_r "${blockStack[@]}" >&2
