Update Git repository using egup-single

diff --git a/cli/stagel-convert b/cli/stagel-convert
--- a/cli/stagel-convert
+++ b/cli/stagel-convert
@@ -771,6 +771,9 @@ for (( i=0; i<tokenCount; i++ )); do
                 command)
                     codegenRoutineName="${tokens[$i]}"
                     case "${tokens[$i]}" in
+                    new|return)
+                        blockStack+=("command" "${tokens[$i]}")
+                        ;;
                     if|until|while)
                         stateStack+=("test")
                         blockStack+=("test" "${tokens[$i]}")
@@ -948,7 +951,7 @@ for (( i=0; i<tokenCount; i++ )); do
     fi
 done
 
-{ [[ "${#blockStack[@]}" == "2" ]] && [[ "${blockStack[0]}" == "root" ]] && [[ "${blockStack[1]}" == "" ]]; } || die "Internal error: not all blocks were consumed, or too many blocks were consumed! This is a bug in the code. Remaining block stack: ${blockStack[*]}"
+{ [[ "${#blockStack[@]}" == "2" ]] && [[ "${blockStack[0]}" == "root" ]] && [[ "${blockStack[1]}" == "" ]]; } || die "Internal error: not all blocks were consumed, or too many blocks were consumed! This is a bug in the StageL transpiler. Remaining block stack: ${blockStack[*]}"
 
 print_r "${stateStack[@]}" >&2
 print_r "${blockStack[@]}" >&2
