Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -84,7 +84,9 @@ elif [[ "--somewhat-verbose" == "$1" ]]; then
     verbose="somewhat"
 fi
 
-if [[ -z "$buildType" ]] || [[ "implementation-parts" == "$buildType" ]]; then
+if [[ -z "$buildType" ]] || [[ "bootstrap" == "$buildType" ]]; then
+    # Test the bootstrap scripts
+    tests/stagel-run-tests || die "StageL tests failed!"
 
 # FIXME: Split up implementation-parts (stagel-bootstrap, stagel, stager-[language])
 if [[ "$1" == "-v" ]]; then
