Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -69,7 +69,7 @@ mkdir -p ./build-temp
 if [[ -n "$buildType" ]]; then
     emberDataDir="$(getEmberDataDir)"
     # Blech! Ensures that all the (non-script parts of) the modules built so far are included in this module, so getEmberDataDir will return all available modules.
-    cp -r "$(getEmberDataDir)/ddc" ./built
+    cp -r "$(getEmberDataDir)/ddc" ./built || die "Could not copy previously installed modules."
 fi
 
 verbose=""
