Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -108,9 +108,9 @@ checkForData() {
     # Check that each module is available
     if [[ -n "$buildType"]]; then
         [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
+        [[ -d "$dceDataDir"/data ]] || die "Could not find dist module while building $buildType."
+        [[ -d "$dceDataDir"/bootstrap ]] || die "Could not find dist module while building $buildType."
+        [[ -d "$dceDataDir"/implementation-parts ]] || die "Could not find dist module while building $buildType."
         [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
     fi
 }
