Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -69,14 +69,12 @@ mkdir -p ./built
 mkdir -p ./build-temp
 
 modules=( dist data bootstrap implementation-parts main web edit-webextension meta )
-for module in "${modules[@]}"; do
-    cp -r "$(getDDCDataDir)/ddc/"* ./built || die "Could not copy previously installed module $module."
-done
 if [[ -n "$buildType" ]] && [[ "dist" != "$buildType" ]]; then
     emberDataDir="$(getDDCDataDir)"
     # Blech! Ensures that all the (non-script parts of) the modules built so far are included in this module, so getDDCDataDir will return all available modules.
-    # The first component built should be "dist".
-    cp -r "$(getDDCDataDir)/ddc/"* ./built || die "Could not copy previously installed modules."
+for module in "${modules[@]}"; do
+    cp -r "$(getDDCDataDir)/ddc/"* ./built || die "Could not copy previously installed module $module."
+done
 fi
 
 verbose=""
