[egup] Update repository metadata

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -70,7 +70,7 @@ mkdir -p ./build-temp
 
 modules=( dist data bootstrap implementation-parts main web edit-webextension meta )
 for module in "${modules[@]}"; do
-    cp -r "$(getDDCDataDir)/ddc/"* ./built || die "Could not copy previously installed modules."
+    cp -r "$(getDDCDataDir)/ddc/"* ./built || die "Could not copy previously installed module $module."
 done
 if [[ -n "$buildType" ]] && [[ "dist" != "$buildType" ]]; then
     emberDataDir="$(getDDCDataDir)"
