Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -76,7 +76,7 @@ if [[ -n "$buildType" ]] && [[ "dist" != "$buildType" ]]; then
         if [[ "$module" == "$buildType" ]]; then
             break
         done
-        cp -r "$(getDDCDataDir)/ddc/"* ./built || die "Could not copy previously installed module $module."
+        cp -r "$(getDDCDataDir)/ddc/$module" ./built || die "Could not copy previously installed module $module."
     done
 fi
 
