Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -82,9 +82,7 @@ fi
 
 if [[ -z "$buildType" ]] || [[ "bootstrap" == "$buildType" ]]; then
     # Test the bootstrap scripts
-    (
-        cd $(pwd)/data/tests || die
-        PATH="$PATH:$(pwd)/data/tests/" stagel-run-bootstrap-tests || die "StageL tests failed!"
+    ./data/tests/stagel-run-bootstrap-tests || die "StageL tests failed!"
 else
     rm scripts/stagel-bootstrap-*
 fi
