Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -110,6 +110,8 @@ checkForData() {
         [[ -d "$dceDataDir"/bootstrap ]] || die "Could not find dist module while building $buildType."
         [[ -d "$dceDataDir"/implementation-parts ]] || die "Could not find dist module while building $buildType."
         [[ -d "$dceDataDir"/dce ]] || die "Could not find dist module while building $buildType."
+        if [[ "edit-webextension" == "$buildType" ]]; then
+        [[ -d "$dceDataDir"/dce ]] || die "Could not find dist module while building $buildType."
     fi
 }
 
