Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -106,12 +106,12 @@ checkForData() {
     # Check that each module is available that is needed for the package modules
     if [[ -n "$buildType"]]; then
         [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/data ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/bootstrap ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/implementation-parts ]] || die "Could not find dist module while building $buildType."
-        [[ -d "$dceDataDir"/dce ]] || die "Could not find dist module while building $buildType."
+        [[ -d "$dceDataDir"/data ]] || die "Could not find data module while building $buildType."
+        [[ -d "$dceDataDir"/bootstrap ]] || die "Could not find bootstrap module while building $buildType."
+        [[ -d "$dceDataDir"/implementation-parts ]] || die "Could not find implementation-parts module while building $buildType."
+        [[ -d "$dceDataDir"/dce ]] || die "Could not find dce module while building $buildType."
         if [[ "edit-webextension" == "$buildType" ]]; then
-            [[ -d "$dceDataDir"/web ]] || die "Could not find dist module while building $buildType."
+            [[ -d "$dceDataDir"/web ]] || die "Could not find web module while building $buildType."
         fi
     fi
 }
