Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -93,7 +93,8 @@ checkForData() {
     # Check that each module is available that is needed for the package modules
     if [[ -n "$buildType" ]]; then
         if [[ "implementation-parts" == "$buildType" ]]; then
-            [[ -d "$dceDataDir"/bootstrap ]] || die "Could not find bootstrap module while building $buildType."
+            # Don't bother checking for bootstrap module; it would be hard to ensure that it's
+            #[[ -d "$dceDataDir"/bootstrap ]] || die "Could not find bootstrap module while building $buildType."
         else
             [[ -d "$dceDataDir"/dist ]] || die "Could not find dist module while building $buildType."
             [[ -d "$dceDataDir"/data ]] || die "Could not find data module while building $buildType."
