Update Git repository using egup-single

diff --git a/support/build-scripts/build b/support/build-scripts/build
--- a/support/build-scripts/build
+++ b/support/build-scripts/build
@@ -7,17 +7,6 @@ trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(p
 
 # Build the EITE implementation.
 
-rm -rf ./built
-mkdir ./built
-mkdir -p ./build-temp
-
-[[ -d /usr/share/eite/wasm-dist-built ]] || die "Couldn't find the WebAssembly toolchain for EITE! Have you installed it yet? (If there's not a package available, you can run make autodep to try to install dependencies. Or, to build and install it by hand, you can make a fresh clone of the ember-information-technology-environment repository and run ./configure; ./support/build-scripts/dist-fetch; make wasm-toolchain; make wasm-toolchain-install)"
-
-cp -r /usr/share/eite/wasm-dist-built ./built/ || die "Couldn't copy the WebAssembly toolchain for EITE!"
-touch ./build-temp/wasm-dist-build-ready
-
-[[ -d ./build-temp/distfiles ]] || die "Make sure the required dependency files are in ./build-temp/distfiles, or run support/dist-fetch to get them from your /usr/portage."
-
 sicmd="./support/build-scripts/build-wrapped"
 #[[ -f "./build-wrapped" ]] && sicmd=./"$sicmd"
 
@@ -54,6 +43,19 @@ elif [[ "$1" == "--no-dist-build" ]]; then
 fi
 
 echo "Building, please wait..."
+
+[[ "$distBuild" == "--dist-build" ]] && rm -rf ./built
+[[ "$distBuild" == "--dist-build" ]] && mkdir ./built
+mkdir -p ./build-temp
+
+[[ -d /usr/share/eite/wasm-dist-built ]] || die "Couldn't find the WebAssembly toolchain for EITE! Have you installed it yet? (If there's not a package available, you can run make autodep to try to install dependencies. Or, to build and install it by hand, you can make a fresh clone of the ember-information-technology-environment repository and run ./configure; ./support/build-scripts/dist-fetch; make wasm-toolchain; make wasm-toolchain-install)"
+
+rm -rf ./built/wasm-dist-built
+cp -r /usr/share/eite/wasm-dist-built ./built/ || die "Couldn't copy the WebAssembly toolchain for EITE!"
+touch ./build-temp/wasm-dist-build-ready
+
+[[ -d ./build-temp/distfiles ]] || die "Make sure the required dependency files are in ./build-temp/distfiles, or run support/dist-fetch to get them from your /usr/portage."
+
 if [[ "$1" == "-v" ]]; then
     shift
     "$sicmd" "$debugBuild" "$typecheckBuild" "$@"
